Terminal: App.c include/App.h Commands.c include/Commands.h History.c include/History.h User.c include/User.h FileManager.c include/FileManager.h main.c
	gcc App.c Commands.c History.c User.c FileManager.c main.c -Wall -Wextra -pedantic -o Terminal
